# Generated by Django 2.1.7 on 2019-03-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='mycover',
            field=models.ImageField(blank=True, upload_to='gallery'),
        ),
    ]
