# Generated by Django 2.1.7 on 2019-03-10 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_mycover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='mycover',
            new_name='cover',
        ),
    ]
